language: rust
rust:
 - 1.8.0
 - nightly
 - beta
 - stable

os:
  - linux
  - osx

notifications:
  webhooks: http://build.servo.org:54856/travis

script:
 - cargo test --features jemalloc
 - "[ $TRAVIS_RUST_VERSION != nightly ] || cargo test --features unstable,jemalloc"
 - "[[ $TRAVIS_RUST_VERSION != nightly && $TRAVIS_RUST_VERSION != beta ]] || cargo test --manifest-path derive/Cargo.toml"

